################### C compiler ########################

# C compiler to use
CC=gcc

# Flags for $(CC)
CFLAGS=-O -g -Wall

################### Java compiler #####################

# Java compiler to use
JAVAC=javac -g

################### JNI interface #####################

## Defaults are set for OpenJDK 17 under Linux/AMD64.
## For other platforms, adjust as required and tell us about it.

# Home location for the JDK.  Only used for setting other variables below. 
JDKHOME=/usr/lib/jvm/java-17-openjdk-amd64

# Where to find the JNI include files (for compiling the OCaml-JNI C stubs)
JNIINCLUDES=-I$(JDKHOME)/include -I$(JDKHOME)/include/linux

# The library to link with to get the JNI
JNILIBS=-ljvm

# Additional link-time options to pass to $(CC) when linking with $(JNILIBS)
JNILIBOPTS=-L$(JDKHOME)/lib \
        -L$(JDKHOME)/lib/server \
        -Wl,-rpath,$(JDKHOME)/lib/$(ARCH)/ \
        -Wl,-rpath,$(JDKHOME)/lib/$(ARCH)/server

# Additional options when compiling the OCaml-JNI C stubs.
JNISTUBSOPTIONS=
