################### C compiler ########################

# C compiler to use
CC=gcc

# Flags for $(CC)
CFLAGS=-O -g -Wall

################### Java compiler #####################

# Java compiler to use
JAVAC=javac -g

################### JNI interface #####################

## Defaults are set for Sun's JDK 1.2.2 under Linux.  
## For other platforms, adjust as required and tell us about it.

# Home location for the JDK.  Only used for setting other variables below. 
JDKHOME=/usr/local/jdk1.2.2

# Where to find the JNI include files (for compiling the OCaml-JNI C stubs)
JNIINCLUDES=-I$(JDKHOME)/include -I$(JDKHOME)/include/linux

# The library to link with to get the JNI
JNILIBS=-ljava

# Additional link-time options to pass to $(CC) when linking with $(JNILIBS)
JNILIBOPTS=-L$(JDKHOME)/jre/lib/i386/ \
        -Wl,-rpath,$(JDKHOME)/jre/lib/i386/ \
        -Wl,-rpath,$(JDKHOME)/jre/lib/i386/classic \
        -Wl,-rpath,$(JDKHOME)/jre/lib/i386/native_threads

# Initial class path to use.  The class path that OCamlJava uses is
# the concatenation of $(BOOTCLASSPATH) (compile-time value)
# with the (run-time) value of the environment variable $CLASSPATH.
BOOTCLASSPATH=\
  $(JDKHOME)/jre/lib/rt.jar:$(JDKHOME)/jre/lib/i18n.jar:$(JDKHOME)/jre/classes

# Additional options when compiling the OCaml-JNI C stubs.
# -DJDK122_LINUX_HACK works around a nasty thread-related bug of
#  Sun's JDK 1.2.2 under Linux
JNISTUBSOPTIONS=-DJDK122_LINUX_HACK
